### ISSUE TITLE
RbNaCl::SecretBuffer backed by sodium_malloc

### ISSUE THREAD

**Issue by tarcieri** [cryptosphere/rbnacl#106]
libsodium 0.7.0 adds `sodium_malloc()`, `sodium_allocarray()`, and `sodium_free()` which manage buffers with guard pages, along with `sodium_mprotect_noaccess()`, `sodium_mprotect_readonly()`, and `sodium_mprotect_readwrite()` for changing memory permissions.

Given these primitives, it should be possible to construct an `RbNaCl::SecretBuffer` for managing things like keying material (and potentially plaintexts) which keeps buffers off-heap and preferentially marks them as `PROT_NONE` when they're not in use.

[Full libsodium 0.7.0 release notes](https://github.com/jedisct1/libsodium/releases/tag/0.7.0)

**Comment by dikaio** [comment]
@tarcieri would you be interested in moving this onto encrypt.io, I've been wanting to get this going on a good open source project.
