### ISSUE TITLE
UTF-8 input to a box is returned as ASCII-8BIT when the box is decrypted

### ISSUE THREAD

**Issue by grempe** [cryptosphere/rbnacl#116]
A box that contains an encrypted UTF-8 string is returned as an ASCII-8BIT encoded string when opened.  Without using .force_encoding('UTF-8') on the decrypted string you can't for example successfully concatenate the output string with a UTF-8 string or compare it to one with the equality operator.

Here is a gist that demonstrates this, using 1, 2, and 3 byte characters in the payload:
https://gist.github.com/grempe/b7fa9dd22e0abfc898ff

I have also created a demo application that shows this in more of a real world scenario by trying to do a round-trip encryption/decryption between rbnacl and libsodium.js:

https://github.com/grempe/libsodium_rb_js_demo/blob/master/myapp.rb#L54

Bug, or intentional? If intentional can you help me understand why and what is the best way to handle this?

Cheers,

Glenn

**Comment by tarcieri** [comment]
We should simply not accept UTF-8 input at all (i.e. raise an exception), and mandate everyone convert strings to ASCII-8BIT ahead of time.

Crypto libraries shouldn't be dealing with string encodings at all, and should always operate on unsigned bytes.

**Comment by grempe** [comment]
So in that case would you include a recommended way to convert UTF-8 text (e.g. supplied by a user and containing 2,3 or 4 byte chars) that needs to be encrypted in a box?  Would it need to be compressed first and de-compressed after decryption?  It can't just be converted to ASCII-8BIT without loss right?

Also, even if you prevent incoming UTF-8 by throwing an exception and assume all incoming text is ASCII-8BIT, that doesn't solve the issue that apparently *all* plain text that comes *out* of the decryption of a box is in ASCII-8BIT and incompatible with what is most likely UTF-8 text that is ubiquitous in a Rails/Sinatra app.  That's where I first saw this issue, in the need to use force_encoding to bring the box plaintext back into UTF-8 land.  That doesn't seem clean either (and in any case all of this is undocumented in rbnacl AFAIK).

What, if any, assumptions are baked into libsodium about this issue? Does it have an opinion?

Cheers

**Comment by tarcieri** [comment]
All inputs and outputs should be unsigned bytes. If Ruby had a `ByteArray` or `ByteBuffer` type, I would use that instead.

It looks like we try to check the encoding here:

https://github.com/cryptosphere/rbnacl/blob/master/lib/rbnacl/util.rb#L90

> So in that case would you include a recommended way to convert UTF-8 text

I'd suggest:

```ruby
str.force_encoding("UTF-8")
```

You're responsible for transcoding from UTF-8 to BINARY when encrypting and transcoding back from BINARY to UTF-8 if that's what you expect. RbNaCl deals exclusively with unsigned bytes (or should)

The point is to not conflate encodings with the crypto operations, lest that lead to vulnerabilities.

> It can't just be converted to ASCII-8BIT without loss right?

Sure it can

**Comment by grempe** [comment]
I don't think you call check_string on the message text.  Only on other things like pub/private keys, and the box key.

Searching for check_string in the gem results in:
https://github.com/cryptosphere/rbnacl/search?utf8=%E2%9C%93&q=check_string

And here is where the potentially offending message is passed into the box (and not checked as far as I can tell):
https://github.com/cryptosphere/rbnacl/blob/02c54ea25adb4a4a18fd14bcc879cd6a249781ee/lib/rbnacl/secret_boxes/xsalsa20poly1305.rb#L65 

Were you suggesting that I manually wrap incoming message text with RbNaCl::Util.check_string?

I'll have to dig some more into the character encoding/decoding issues.  This is an area that I'm sure many struggle with (and for my demo app I'm trying to do it across Javascript w/ libsodium.js and Ruby transparently adds to the complexity).

**Comment by tarcieri** [comment]
> Were you suggesting that I manually wrap incoming message text with RbNaCl::Util.check_string?

No, really RbNaCl should assert up front that all strings are ASCII-8BIT/BINARY. What you should be doing as a user of the library is converting all inputs (keys, plaintexts, and ciphertexts) into BINARY format with `str.force_encoding("BINARY")` then round-trip that back to your expected encoding when you decrypt.

Sorry this is such a mess, but that's string encodings for you.

**Comment by grempe** [comment]
OK, I'll give that a go.  Optimally this should be documented in rbnacl, otherwise it becomes one of those 'crypto landmines' that nacl/libsodium is trying to help us avoid :-)

**Comment by grempe** [comment]
PS - Thanks for the very quick responses.

**Comment by Asmod4n** [comment]
It doesn't really matter what encoding ruby uses for a plaintext when you encrypt something, as long as the size of that plaintext is checked via ```.bytesize```.

When you decrypt something tho, C doesn't know anything about the ruby encoding of the plaintext and you get a BINARY string back, if you want to know what encoding the original plaintext used you could use the AEAD mode of libsodium and put the original encoding of the plaintext in the ```additional_data``` parameter. If you decrypt that ciphertext then and the additional data doesn't match libsodium returns a error.

**Comment by grempe** [comment]
Thanks.  I do have things working pretty well round trip now between libsodium.js and rbnacl after Tony's suggested changes.  @Asmod4n I will look into AEAD mode though, but I only plan to use UTF-8 so it may not be worth the extra effort for this use.

Here is the little prototype app running on Heroku.  The Sinatra app (Alice) encrypts some text for Bob (Client side libsodium.js) and checks whether the decrypted ciphertext matches the original plaintext.

If you submit the form at the bottom your do the trip in the opposite direction, from Bob client to Alice server.

In both cases I'm using a string with up to 4 byte chars, ending with the famous 'pile of poo'.  It is working cleanly in both directions now (its not very pretty too look at though :-).

https://libsodium-rb-js-demo.herokuapp.com/

The source code for that is linked above.  I'll leave it to you both to decide if you want to reject non-BINARY messages, or perhaps simply do the force_encoding('BINARY') transparently on behalf of the user.  This appears to be the general approach that libsodium.js takes. Just handle it for the user.

https://github.com/jedisct1/libsodium.js

````
Binary input buffers should be Uint8Array objects. However, if a string is given instead, the wrappers will automatically convert the string to an array containing a UTF-8 representation of the string.
````

Thanks,

Glenn

**Comment by Asmod4n** [comment]
You could also just call ```.force_encoding(Encoding.default_external)``` so you get a string back like ruby would give you by default when it comes from a external source, which is UTF-8 unless changed.

**Comment by Asmod4n** [comment]
btw, i hope you won't load libsodium.js via a <script> tag from a web server, its like allowing anyone to run eval() on your server.

**Comment by Asmod4n** [comment]
Or from a web server at all.

**Comment by grempe** [comment]
@Asmod4n Sorry, could you elaborate on that?  I know the general concerns about 'javascript crypto' and I am keeping that in mind.  But why would loading libsodium.js from a webserver in a script tag (over HTTPS) be like exposing eval()?

libsodium.js is designed to be loaded exactly like that, and its in the README:
https://github.com/jedisct1/libsodium.js

Actually, this is exactly why I wanted to use a libsodium based library in ruby (exploring Elixir and Erlang libs as well for server side) since I can get cross platform public key encryption that will work in both the browser and on the server side, generating encrypted/signed text that is usable in either context and could be sent from server to client and vice-versa.  I am not currently aware of any other way (I am trying to encrypt some data which ONLY ever exists in a browser context, which I don't want to send to any server prior to being encrypted. It must never be stored or transmitted unencrypted even over HTTPS).  Think end-to-end (browser to browser) encrypted data that needs to be stored on a server, but where the server never sees the private keys. But there are some cases where the server would actually be the recipient of encrypted data for its own use, or the originator of data destined to be decrypted by a browser client with the private key loaded).

Your thoughts or options for other approaches much appreciated.  Happy to pick your brains outside the context of this Github issue as well. :-)

**Comment by Asmod4n** [comment]
The issue with Javascript Crypto is that you have run on your crypto code in a seperate Javascript Context (Webbrowser extension) or else a attacker could overwrite the Random Number Generator.

Because unlike Ruby Javascript lacks a way to stop a Object from being modified.

In Ruby you can freeze a Class/Module so its methods cannot be monkey patched, Javascript lacks such a thing.

**Comment by grempe** [comment]
Hmmm.  Well, I understand the generalized concerns some have raised about crypto in a browser context and there are certainly aspects of that that are real and there are a number of ways to go about that kind of attack.

I'm not sure I would make the argument that Ruby is immune to this do to freezing classes or modules though.  RbNacl does not use freeze in this context at all (and I'm not sure your use of freeze is even possible at the class or module level).  And if someone has access to your server code you are certainly just as vulnerable whether by hacking or compelled changes by a government.

In any case, we are off topic here and I think my original questions have been answered so I'll go ahead and close this issue.  Tony feel free to re-open if you want to use this as a reminder for any changes to force BINARY encoding of the message to be encrypted if thats what you indeed want to do.

Cheers,

Glenn

**Comment by tarcieri** [comment]
The only solution is to ensure you control 100% of the JavaScript running on the page. One tool that helps with this is Content Security Policy:

https://en.wikipedia.org/wiki/Content_Security_Policy

CSP allows you to ban inline scripts and ensure that all scripts on the page are loaded from a particular location that you control.

Also make absolutely sure you're using HTTPS to serve all content!

**Comment by grempe** [comment]
Yes, thanks Tony, thats a good reminder.  I've been looking into CSP already. And when (if?) I bring my idea to fruition it will absolutely be HTTPS only and all code and content would be served by my server alone (no CDN) over HTTPS.  All of the above code is exploratory in nature. Thanks again for the help.  When I get a little further down the road maybe I can reach out to you for a review and comments.
