### ISSUE TITLE
Wiki: SALTBYTES typo in wiki code for Password-Hashing

### ISSUE THREAD

**Issue by soumyaray** [cryptosphere/rbnacl#119]
Wiki Page: https://github.com/cryptosphere/rbnacl/wiki/Password-Hashing

`SALT_BYTES` ==> `SALTBYTES`

`salt = RbNaCl::Random.random_bytes(RbNaCl::PasswordHash::SCrypt::SALT_BYTES)`

should be:

`salt = RbNaCl::Random.random_bytes(RbNaCl::PasswordHash::SCrypt::SALTBYTES)`

**Comment by namelessjon** [comment]
Fixed, thanks!
