### ISSUE TITLE
Report of A Successful Windows User

### ISSUE THREAD

**Issue by jarmo** [cryptosphere/rbnacl#121]
In README under `Supported Platforms` Windows is mentioned like this:
> In theory Windows should be supported, although there are not yet any reports of successful Windows users.

I'm creating this issue to report a successful use of `RbNaCl` under Windows.

This is how to install `RbNaCl` under Windows and maybe this issue can be pointed out from a wiki or README itself for others.

* Download pre-built library of `libsodium` from https://download.libsodium.org/libsodium/releases/. I used latest version at the time of creating this issue `libsodium-1.0.3-msvc.zip`;
* Extract that pre-build library of `libsodium` to some directory;
* Install `RbNaCl` normally - `gem install rbnacl`;
* Load `RbNaCl` like this:
```ruby
# Set libsodium gem path.
# Please note that I got it working only with v120 and not the latest of v140.
::RBNACL_LIBSODIUM_GEM_LIB_PATH = "d:/downloads/libsodium-1.0.3-msvc/Win32/Release/v120/dynamic/libsodium.dll"

# Should not throw any errors
require 'rbnacl'

# Use RbNaCl as you would normally
```

Here's some additional information about my environment:
```
C:\Users\Jarmo>systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows 8.1 Pro
OS Version:                6.3.9600 N/A Build 9600

C:\Users\Jarmo>ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [i386-mingw32]

C:\Users\Jarmo>gem which ffi
c:/bin/Ruby22/lib/ruby/gems/2.2.0/gems/ffi-1.9.10-x86-mingw32/lib/ffi.rb

C:\Users\Jarmo>gem which rbnacl
c:/bin/Ruby22/lib/ruby/gems/2.2.0/gems/rbnacl-3.2.0/lib/rbnacl.rb
```

If yours differs then you should try different versions (e.g. 32bit vs 64bit).

**Comment by Asmod4n** [comment]
You most likely need a new visual studio c++ library redistributable.

**Comment by Asmod4n** [comment]
For v140 ^^

**Comment by namelessjon** [comment]
Thanks for this report.  Excellent to see it works on Windows

**Comment by tarcieri** [comment]
I adapted your notes to a wiki entry which I'll link from the README:

https://github.com/cryptosphere/rbnacl/wiki/Windows-Installation

**Comment by tarcieri** [comment]
PR to change the README in #123

**Comment by jarmo** [comment]
That's cool, but wouldn't it suit more into `Installation` paragraph?
