### ISSUE TITLE
Update for the scrypt API

### ISSUE THREAD

**Issue by paragonie-scott** [cryptosphere/rbnacl#130]
Hi Tony,

Would you object if I sent a pull request that exposes the equivalent of `crypto_pwhash_scryptsalsa208sha256_str()` and `crypto_pwhash_scryptsalsa208sha256_str_verify()`?

(And then replicate the effort for simply `crypto_pwhash_str()` and `crypto_pwhash_str_verify()`.)

**Comment by namelessjon** [comment]
Please do!

**Comment by tarcieri** [comment]
Yes, this is fine :+1:

**Comment by tarcieri** [comment]
I believe this was addressed in #144?

**Comment by paragonie-scott** [comment]
Yep.
