### ISSUE TITLE
How does your public key encryption compare to RSA + AES?

### ISSUE THREAD

**Issue by NullVoxPopuli** [cryptosphere/rbnacl#133]
I was reading this: https://github.com/cryptosphere/rbnacl/wiki/Public-Key-Encryption

and wondering how it would compare to RSA public/private keys being used to encrypt an AES key and iv (which is in turn used to decrypt the final message of N length)

This is what I'm currently doing: 
https://github.com/NullVoxPopuli/meshchat/blob/master/lib/meshchat/encryption/aes_rsa.rb#L21

Is XSalsa20, Poly1305 MAC, and Curve25519 better than that application of AES and RSA? if so, how / why?

**Comment by tarcieri** [comment]
`crypto_box` is a hybrid cryptosystem (similar to an [ECIES](https://en.wikipedia.org/wiki/Integrated_Encryption_Scheme)) which uses Curve25519 ECDH for key exchange and XSalsa20Poly1305 for authenticated symmetric encryption.

I wouldn't necessarily say XSalsa20 is "better" than AES: on modern Intel CPUs AES is hardware accelerated. XSalsa20Poly1305 provides an authenticated construct similar than GCM. On the NaCl web site, AES-GCM was listed as another option for the `crypto_secretbox` symmetric encryption primitive. libsodium now implements it, although RbNaCl does not yet expose it (but only for systems that support hardware acceleration)

Regarding RSA: it's fraught with problems. The large keys make it slow, require use of bignums, and therefore make it difficult to implement in constant time. Poor padding modes like PKCS#1v1.5 have plagued RSA for years.
