### ISSUE TITLE
RDoc links on RbNaCl HMAC wiki page are broken

### ISSUE THREAD

**Issue by grempe** [cryptosphere/rbnacl#134]
On HMAC wiki page:
https://github.com/cryptosphere/rbnacl/wiki/HMAC

The two rdoc page links are broken:

http://rubydoc.info/github/cryptosphere/rbnacl/master/Crypto/HMAC/SHA256
http://rubydoc.info/github/cryptosphere/rbnacl/master/Crypto/HMAC/SHA512256

Should be:

http://www.rubydoc.info/github/cryptosphere/rbnacl/master/RbNaCl/HMAC/SHA256
http://www.rubydoc.info/github/cryptosphere/rbnacl/master/RbNaCl/HMAC/SHA512256

**Comment by tarcieri** [comment]
Thanks! Fixed
