### ISSUE TITLE
Secret Key Encryption with SimpleBox

### ISSUE THREAD

**Issue by atmos** [cryptosphere/rbnacl#138]
Hi, thanks for writing this and providing the gem that bundles libsodium, it was super easy to migrate from an older encryption library with weaker ciphers.

I'm using secret key encryption with SimpleBox and was wondering what the advised way to generate and store the secret key in your shell environment. What I've gone with is something like this:

```
dd if=/dev/urandom bs=32 count=1 2>/dev/null | openssl base64
```

That value gets set in my runtime environment and then I'm using SimpleBox like so:

```ruby
key = ENV["RBNACL_SECRET"].unpack("m0").first
box = RbNaCl::SimpleBox.from_secret_key(key)
box.encrypt(value)
```

* Is the way that I'm fetching my key from the environment acceptable for key usage?
* Should I be reading more information from dd for key generation?

Thanks.

**Comment by tarcieri** [comment]
I generally wouldn't recommend environment variables for storing keys as they aren't typically expected to be secrets so they often wind up logged by things like exception reporters. If you're confident that's not the case for you then they're ok.

That's the correct key size. RbNaCl would (or should!) throw an exception if it wasn't.
