### ISSUE TITLE
Friendlier password interface

### ISSUE THREAD

**Issue by csuhta** [cryptosphere/rbnacl#140]
This is an offer to submit a pull request that would implement an alternate, but friendlier password hashing interface that uses `RbNaCl::PasswordHash`. Asking here to see if you're open to it before I do any work.

The goals would be to make sure other developers can easily do the right thing with their passwords and move on:

- A module-based interface that only requires user input and handles it correctly
- Configurable, but if the developer doesn't do anything, the defaults are not a footgun
- The hashed output is a single ASCII string that can be stored in just one database column
- The string contains all of the parameters, so that you can "upgrade" passwords later but still check old passwords

(This is mostly how the bcrypt-ruby gem works, and why I think it's so popular)

Example code:

```ruby
plaintext_password = "super-secret" # Get a password from the user somehow

stored_password = RbNaCl::Password.create(plaintext_password)
# => "$nacl$1048576$16777216$8trKfon7onGxdB00WvcoNhYiVJcujfKhT3Ln8AFQeXU$lv80U1i-zK8WCDsWY-y1z6oQF9d2nB2HWhbqNX5JocIKTUQp-UuV_buJc62ZFeOnYVDhWEQF0DAsYYMlMe_XAw"

# Then later…
plaintext_password = "super-secret" # Get the password the user is signing in with
RbNaCl::Password.valid?(plaintext_password, stored_password)
# => true
```

In this example: 

- `1048576` is the `opslimit`
- `16777216` is the `memlimit`
- `8trKfon7onGxdB00WvcoNhYiVJcujfKhT3Ln8AFQeXU` is the base64-ed salt
- `lv80U1i-zK8WCDsWY-y1z6oQF9d2nB2HWhbqNX5JocIKTUQp-UuV_buJc62ZFeOnYVDhWEQF0DAsYYMlMe_XAw` is the base64-ed hash

Continuing example with upgrading:

```ruby
# Optional configuration example, new passwords use these limits
RbNaCl::Password.preferred_opslimit = 2**21
RbNaCl::Password.preferred_memlimit = 2**25

# Still works
RbNaCl::Password.valid?(plaintext_password, stored_password)
# => true

# But also this is true because the limits on the stored 
# password are not the same as the preferred limits now
RbNaCl::Password.needs_upgrade?(stored_password)
# => true
```

What do you think? Questions?

**Comment by tarcieri** [comment]
The general philosophy of this library is to be a lightweight wrapper around libsodium without providing complicated facilities beyond what's already in libsodium.

What you're proposing sounds interesting, but I think it probably belongs in a separate gem, especially one which can pull in multiple password hashing backends beyond the ones RbNaCl provides.

**Comment by csuhta** [comment]
Ok, that's definitely reasonable! 

Thanks for the suggestion. I'll ping here if I end up making such a gem, just for your FYI.

**Comment by elijh** [comment]
@csuhta actually, I think libsodium actually has all the things you want, it has just not been exposed in rbnacl until now:

```ruby
digest = RbNaCl::PasswordHash.argon2_str(password)
=> "$argon2i$v=19$m=32768,t=4,p=1$aRJ9T7ZVYTVIpkJCbCy9bw$hWiOb6QwZ591nV8tXAfqSLuPD8yqI+ZN/B7ajmU33Zc"
...
RbNaCl::PasswordHash.argon2_valid?(password, digest)
=> true
```

**Comment by dkam** [comment]
Would it be possible to have this example provided by @elijh added to the [Password Hashing](https://github.com/crypto-rb/rbnacl/wiki/Password-Hashing) wiki page?

**Comment by tarcieri** [comment]
@dkam added!
