### ISSUE TITLE
Errors in `AEAD: ChaCha20Poly1305` Code Example of `Secret Key Encrption` Wiki Page

### ISSUE THREAD

**Issue by zhenkyle** [cryptosphere/rbnacl#149]
I'm new to `rbnacl`. I faied to run the `AEAD: ChaCha20Poly1305` Code Example of the [Secret Key Encrption Wiki Page](https://github.com/cryptosphere/rbnacl/wiki/Secret-Key-Encryption) . After spending 30 mins to figure out why, I found the errors.

    ad = ""         # Additional data sent *in the clear* to be authenticated
    ciphertext = cipher.encrypt(nonce, ad, message)
    #=> "..." # string of random looking bytes, 16 bytes longer than message.

should be

    ciphertext = cipher.encrypt(nonce, message, ad)

and

    # Decrypt a message, passing in the same nonce and additional data we used to encrypt
    decrypted_message = cipher.decrypt(nonce, ad, ciphertext)
    #=> "..."

should be

    decrypted_message = cipher.decrypt(nonce, ciphertext, ad)

**Comment by tarcieri** [comment]
Thanks! Fixed
