### ISSUE TITLE
RbNaCl::VerifyKey.new(bin_pubkey) seems broken

### ISSUE THREAD

**Issue by paddor** [cryptosphere/rbnacl#151]
It should be possible to create a VerifyKey from an `RbNaCl::PublicKey#to_bytes`, right?
Unfortunately this seems to be broken. The message can't be authenticated. It only works when using `RbNaCl::SigningKey#verify_key`.

```ruby
#require 'rbnacl'
require 'rbnacl/libsodium' # doesn't matter which one

privkey = RbNaCl::PrivateKey.generate
bin_privkey = privkey.to_bytes
bin_pubkey = privkey.public_key.to_bytes

puts "bin_privkey = #{bin_privkey.dump} (#{bin_privkey.bytesize} bytes)"
puts "bin_pubkey  = #{bin_pubkey.dump} (#{bin_pubkey.bytesize} bytes)"

sk = RbNaCl::SigningKey.new bin_privkey
vk = RbNaCl::VerifyKey.new  bin_pubkey
#vk = sk.verify_key # <-- with this it works

dump = 'dump'
sig = sk.sign dump
puts "signature = #{sig.dump}"

vk.verify sig, dump
puts 'all good.'
```

Output when it fails:
```
bin_privkey = "\xED\xAC\xDE\xCE\xC4c<\xF3\xD8\xEB\x04\xD1\xAB\x84\x8E\x96\x991\xC9m\xBE\xC5\x9C9\xDD\xF8\xE56\x85E\xBF\x8B" (32 bytes)
bin_pubkey  = "\a\xB4uW\xF6ho\xA9\x12!\a\xFD\xBB]S\x97\x97>\x93\xE9z\xFBx\x11\x89\x0F\xA0\xCF\xAC\xA7\xE1M" (32 bytes)
signature = "2\xF4Cu\xCE\xD8\xC2\xC2K\x83QDm\xC1\xBAw\x18B\x84\xE3E\xD4\xD7Y\x03\xDF\xBB]Z\xB6\xFDn\xCCn6g\xC7\x10\xF6\x04\x97\xF1Q\xAD\xF4k\x15<:\x9BR\xBA\x1F\x87\x98\x83\x89S\r\xF1\xAB\x939\x0E"
/home/paddor/.gem/ruby/2.3.1/gems/rbnacl-4.0.1/lib/rbnacl/signatures/ed25519/verify_key.rb:56:in `verify': signature was forged/corrupt (RbNaCl::BadSignatureError)
        from msg_auth.rb:33:in `<main>'
```

Any help is appreciated.

**Comment by tarcieri** [comment]
`RbNaCl::PublicKey` and `RbNaCl::VerifyKey` are two completely different kinds of keys:

```
>> RbNaCl::PublicKey
=> RbNaCl::Boxes::Curve25519XSalsa20Poly1305::PublicKey
>> RbNaCl::VerifyKey
=> RbNaCl::Signatures::Ed25519::VerifyKey
```

`PublicKey` is an "encryption" key, i.e. X25519 Diffie-Hellman static key represented as a Montgomery x-coordinate

`VerifyKey` is a digital signature key, i.e. an Edwards (x,y) coordinate pair w\ point compression

They are not interchangeable. See https://github.com/jedisct1/libsodium/issues/335 for more discussion.

**Comment by paddor** [comment]
Thanks for the answer. So is there no way to verify a signature using only some kind of public key? What if the message recipient does not have the private key?

**Comment by tarcieri** [comment]
@paddor `RbNaCl::VerifyKey` is the corresponding public key for verifying signatures

**Comment by paddor** [comment]
Thanks.

**Comment by paddor** [comment]
Just to be sure whether this is secure: Assuming a system of nodes, where each has its own private key. A shared configuration (a file) contains the associated public keys (`RbNaCl::PublicKey#to_bytes`), as well as the verification keys derived from the private keys (e.g. `RbNaCl::SigningKey.new(bin_sk).verify_key.to_bytes`). The public keys are used on ZMQ CURVE sockets to authenticate remote sockets, as well as encrypt (and authenticate) traffic. The verification keys are used to authenticate messages, previously signed using RbNaCl::SigningKey (especially messages that have traveled multiple hops within the system, to verify the authenticity of messages end-to-end).

Is this save, assuming the private keys themselves stay private? Maybe it's a no-go to derive the verification keys from the very same private keys? Or maybe there are limits as to the number of messages that can be signed? Thanks.

**Comment by tarcieri** [comment]
That sounds ok, although based on your description I'm not sure what you're using `RbNaCl::PublicKey` for

**Comment by paddor** [comment]
Thanks for the answer.

`RbNaCl::PublicKey` would be used indirectly to get the associated public key of the freshly generated private key to be able to put the public key into the shared configuration, e.g. `sk.public_key.to_bytes`.

**Comment by namelessjon** [comment]
It's best practice to use separate keys for signing and encryption, and for them to be independent.  Yes, by using two keypairs (one PublicKey/SecretKey, one VerifyKey/SigningKey) you'd be doubling the size of your key.  But that's only to 64 bytes (or 128 bytes for the private parts), which seems entirely manageable, especially in the context of presumably other metadata about the node?

While I don't think in this particular instance you're creating a vulnerability (due to the properties of the two algorithms), I'm not paid to think about this professionally or academically.

**Comment by tarcieri** [comment]
Moreover, without XEdDSA the keys for D-H (X25519) and signatures (Ed25519) are not compatible
