### ISSUE TITLE
Wiki Docs for Argon2

### ISSUE THREAD

**Issue by grempe** [cryptosphere/rbnacl#155]
I think there is an error in the docs on the wiki for Argon2 salt. Probably just a copy/paste err.

https://github.com/cryptosphere/rbnacl/wiki/Password-Hashing

is 32:
```
# Generate a random salt (libsodium enforces 32-byte salts)
salt = RbNaCl::Random.random_bytes(RbNaCl::PasswordHash::SCrypt::SALTBYTES)
```

should be 16 and `RbNaCl::PasswordHash::Argon2::SALTBYTES`:
```
# Generate a random salt (libsodium enforces 16-byte salts)
salt = RbNaCl::Random.random_bytes(RbNaCl::PasswordHash::Argon2::SALTBYTES)
```

Maybe also make mention of the options for `OPSLIMIT_*` and `MEMLIMIT_*` ?

RbNaCl::PasswordHash::Argon2::OPSLIMIT_MODERATE
RbNaCl::PasswordHash::Argon2::MEMLIMIT_MODERATE

**Comment by tarcieri** [comment]
Fixed. I also invited you to be a collaborator of the project if you'd like to improve the documentation and/or code.

**Comment by grempe** [comment]
That's great. Thanks for the invite Tony, and the trust.

**Comment by tarcieri** [comment]
You've been helping clean up various messes I've made for awhile now, so I think you deserve it :wink:
