### ISSUE TITLE
Nonce was 4 bytes (Expected 24)

### ISSUE THREAD

**Issue by chris-roerig** [cryptosphere/rbnacl#158]
I'm developing a SimpleBox wrapper that would allow me to encrypt/decrypt. I'm using an initializer file to read in the secret key. I'm able to encrypt but decrypting is throwing this error:

`RbNaCl::LengthError: Nonce was 4 bytes (Expected 24)`

The error is thrown in `Crypt.decrypt`.

My gut is telling me there is a problem with the key but any insight would be helpful.

```
class Crypt
  def self.decrypt(encrypted = "")
    RbNaCl::SimpleBox.from_secret_key(::SECRET_KEY).decrypt(encrypted)
  end

  def self.encrypt(plaintext = "")
    RbNaCl::SimpleBox.from_secret_key(::SECRET_KEY).encrypt(plaintext)
  end
end
```

```
# in initializer
SECRET_KEY = IO.binread(File.join(Rails.root, "secret_key"))
```

```
# How I created the key file via rake task
File.open(File.join(Rails.root, "secret_key"), "wb") do |f|
  f.write(RbNaCl::Random.random_bytes(RbNaCl::SecretBox.key_bytes))
end
```

**Comment by tarcieri** [comment]
If you're getting this error, it's a bug in the library. Although something of a curious one. I'll have to investigate...

**Comment by chris-roerig** [comment]
I should have noted above that the data is encrypted then stored in a binary column in MySql. I retrieve the data and try to decrypt it. A simple example would be:

```
name = Crypt.encrypt("test")
foo = Foo.create(name: name)
Crypt.decrypt(foo.name)
```

**Comment by chris-roerig** [comment]
Sorry to have opened this issue. It was actually a bug in my code. Thanks for looking into this however.

**Comment by Park1ker** [comment]
> I should have noted above that the data is encrypted then stored in a binary column in MySql. I retrieve the data and try to decrypt it. A simple example would be:
> 
> ```
> name = Crypt.encrypt("test")
> foo = Foo.create(name: name)
> Crypt.decrypt(foo.name) # this is where the error happens
> ``
You can drop your wallet private key so I can help you scan on my board to know if it has a web virus Man function
